propper svg/math elements
karaxnim/karax pull request #271
Opened 2023-10-16 20:51 UTC by choltreppe

ok, so here it is. I did the same test as in the .yml file so it should be all good

2023-10-16 21:01 UTC, geotre requested changes

2023-10-16 21:01 UTC, geotre commented on karax/karax.nim
> +        document.createElementNS(svgNamespace, $n.kind)
```suggestion
        document.createElementNS(svgNamespace, toTag[n.kind])
```

for consistency if not correctness

2023-10-16 21:01 UTC, geotre commented on karax/karax.nim
> +        document.createElementNS(mathNamespace, $n.kind)
```suggestion
        document.createElementNS(mathNamespace, toTag[n.kind])
```

2023-10-16 21:05 UTC, choltreppe commented on karax/vdom.nim
> +
ah yep thats smart

2023-10-16 22:52 UTC, geotre commented on karax/karax.nim
> +        document.createElementNS(svgNamespace, $n.kind)
Good catch

My concern with using `$n.kind` is that some svg elements (from a quick look at the list - `stext`, `discard`, `set`) may not work correctly

I'm not sure if toTag needs to convert to uppercase, tests pass without it. Any idea @Araq? It was added in [this PR](https://github.com/karaxnim/karax/commit/be0f9c9e08b85591b38bd784bb3f6013e6856a18)

2023-10-18 10:26 UTC, choltreppe commented on karax/karax.nim
> +        document.createElementNS(svgNamespace, $n.kind)
no they all have the correct string value. for example `stext = "text"`. all `toTag` does is uppercasing and casting to `kstring`. I updated it now to not uppercase

2023-10-20 15:18 UTC, geotre approved these changes

2023-10-20 15:26 UTC, geotre commented
Looks great. Good job @choltreppe

2023-10-20 15:26 UTC, merged